language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install coveralls
script:
  - pytest finitediff/unit_tests.py
  - coverage run --source=finitediff finitediff/unit_tests.py
after_success:
  - coveralls
