language: python
python:
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install coveralls
script:
  - pytest finitediff/unit_tests.py
  - coverage run --source=finitediff finitediff/unit_tests.py
after_success:
  - coveralls
